### ISSUE TITLE
When opening an empty feature file,  org.netbeans.modules.parsing.spi.ParseException is thrown. 

### ISSUE THREAD

**Issue by Downright-Development** [Downright-Development/Cucumberbeans#34]
When opening the empty feature file the following exception is thrown.

java.lang.NullPointerException
	at org.netbeans.modules.csl.navigation.ElementScanningTask$MimetypeRootNode.<init>(ElementScanningTask.java:363)
	at org.netbeans.modules.csl.navigation.ElementScanningTask$MimetypeRootNode.<init>(ElementScanningTask.java:337)
	at org.netbeans.modules.csl.navigation.ElementScanningTask$1.run(ElementScanningTask.java:187)
	at org.netbeans.modules.parsing.impl.TaskProcessor.callUserTask(TaskProcessor.java:609)
	at org.netbeans.modules.parsing.api.ParserManager$UserTaskAction.run(ParserManager.java:153)
	at org.netbeans.modules.parsing.api.ParserManager$UserTaskAction.run(ParserManager.java:137)
	at org.netbeans.modules.parsing.impl.TaskProcessor$2.call(TaskProcessor.java:204)
	at org.netbeans.modules.parsing.impl.TaskProcessor$2.call(TaskProcessor.java:201)
	at org.netbeans.modules.masterfs.filebasedfs.utils.FileChangedManager.priorityIO(FileChangedManager.java:176)
	at org.netbeans.modules.masterfs.providers.ProvidedExtensions.priorityIO(ProvidedExtensions.java:360)
	at org.netbeans.modules.parsing.nb.DataObjectEnvFactory.runPriorityIO(DataObjectEnvFactory.java:141)
	at org.netbeans.modules.parsing.impl.Utilities.runPriorityIO(Utilities.java:88)
	at org.netbeans.modules.parsing.impl.TaskProcessor.runUserTask(TaskProcessor.java:201)
Caused: org.netbeans.modules.parsing.spi.ParseException
	at org.netbeans.modules.parsing.impl.TaskProcessor.runUserTask(TaskProcessor.java:209)
	at org.netbeans.modules.parsing.api.ParserManager.parse(ParserManager.java:104)
[catch] at org.netbeans.modules.csl.navigation.ElementScanningTask.computeStructureRoot(ElementScanningTask.java:162)
	at org.netbeans.modules.csl.navigation.BreadCrumbsTask$1.run(BreadCrumbsTask.java:128)
	at org.netbeans.modules.csl.navigation.ElementScanningTask.runWithCancelService(ElementScanningTask.java:279)
	at org.netbeans.modules.csl.navigation.BreadCrumbsTask.run(BreadCrumbsTask.java:102)
	at org.netbeans.modules.csl.navigation.BreadCrumbsTask.run(BreadCrumbsTask.java:81)
	at org.netbeans.modules.parsing.impl.TaskProcessor.callParserResultTask(TaskProcessor.java:584)
	at org.netbeans.modules.parsing.impl.TaskProcessor$RequestPerformer.run(TaskProcessor.java:809)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:304)
	at org.netbeans.modules.parsing.impl.TaskProcessor$RequestPerformer.execute(TaskProcessor.java:725)
	at org.netbeans.modules.parsing.impl.TaskProcessor$CompilationJob.run(TaskProcessor.java:686)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1443)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:68)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:303)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2058)
WARNING [org.netbeans.modules.csl.navigation.ElementScanningTask]

**Comment by Downright-Development** [comment]
Discovered the reason this NPE is thrown.  The NPE is thrown due to the "feature" parser rule.  The parse indicates that the word "feature" is a REQUIREMENT.  When the "empty" feature file is created, it does not contain the "feature:" construct.

**Comment by Chris2011** [comment]
Unfortunately, I still got an NPE:

```
java.lang.NullPointerException
	at org.netbeans.modules.csl.navigation.ElementScanningTask$MimetypeRootNode.<init>(ElementScanningTask.java:363)
	at org.netbeans.modules.csl.navigation.ElementScanningTask$MimetypeRootNode.<init>(ElementScanningTask.java:337)
	at org.netbeans.modules.csl.navigation.ElementScanningTask$1.run(ElementScanningTask.java:187)
	at org.netbeans.modules.parsing.impl.TaskProcessor.callUserTask(TaskProcessor.java:609)
	at org.netbeans.modules.parsing.api.ParserManager$UserTaskAction.run(ParserManager.java:153)
	at org.netbeans.modules.parsing.api.ParserManager$UserTaskAction.run(ParserManager.java:137)
	at org.netbeans.modules.parsing.impl.TaskProcessor$2.call(TaskProcessor.java:204)
	at org.netbeans.modules.parsing.impl.TaskProcessor$2.call(TaskProcessor.java:201)
	at org.netbeans.modules.masterfs.filebasedfs.utils.FileChangedManager.priorityIO(FileChangedManager.java:176)
	at org.netbeans.modules.masterfs.providers.ProvidedExtensions.priorityIO(ProvidedExtensions.java:360)
	at org.netbeans.modules.parsing.nb.DataObjectEnvFactory.runPriorityIO(DataObjectEnvFactory.java:141)
	at org.netbeans.modules.parsing.impl.Utilities.runPriorityIO(Utilities.java:88)
	at org.netbeans.modules.parsing.impl.TaskProcessor.runUserTask(TaskProcessor.java:201)
Caused: org.netbeans.modules.parsing.spi.ParseException
	at org.netbeans.modules.parsing.impl.TaskProcessor.runUserTask(TaskProcessor.java:209)
	at org.netbeans.modules.parsing.api.ParserManager.parse(ParserManager.java:104)
[catch] at org.netbeans.modules.csl.navigation.ElementScanningTask.computeStructureRoot(ElementScanningTask.java:162)
	at org.netbeans.modules.csl.navigation.BreadCrumbsTask$1.run(BreadCrumbsTask.java:128)
	at org.netbeans.modules.csl.navigation.ElementScanningTask.runWithCancelService(ElementScanningTask.java:279)
	at org.netbeans.modules.csl.navigation.BreadCrumbsTask.run(BreadCrumbsTask.java:102)
	at org.netbeans.modules.csl.navigation.BreadCrumbsTask.run(BreadCrumbsTask.java:81)
	at org.netbeans.modules.parsing.impl.TaskProcessor.callParserResultTask(TaskProcessor.java:584)
	at org.netbeans.modules.parsing.impl.TaskProcessor$RequestPerformer.run(TaskProcessor.java:809)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:304)
	at org.netbeans.modules.parsing.impl.TaskProcessor$RequestPerformer.execute(TaskProcessor.java:725)
	at org.netbeans.modules.parsing.impl.TaskProcessor$CompilationJob.run(TaskProcessor.java:686)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1443)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:68)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:303)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2058)
```
It say: A org.netbeans.modules.parsing.spi.ParserException exception has occured but it is a NPE.

Steps to reproduce:
- I merged your master into my master so everything is up to date.
- I built and ran your project.
- I opened your project in the dev environment, because I don't have a proper feature file to test.
- I navigated to the package `development.downright.cucumberbeans.resources.xml` in the "Other Sources" section
- I opened GherkinEmpty.feature file
- I did a "Select All" and removed everything
- Right after deleting all, I got the exception.
